### ISSUE TITLE
Windows CE Games

### ISSUE THREAD

**Issue by wicksand420** [Rinnegatamante/flycast-vita-Compatibility#190]
All Windows CE games are crashing

**Comment by wicksand420** [comment]
A good majority of the crashing games are powered by Microsoft Windows CE, I'd say at least 89%

**Comment by Rinnegatamante** [comment]
Open single issues for games. This repository issue tracker is downloaded by the compat list website.

**Comment by wicksand420** [comment]
Sorry, I'm going to keep adding to this list when I find more Windows CE games though, its fine its closed

**Comment by wicksand420** [comment]
I found info about Windows CE enhanced games, you need a 64 bit architecture and Vita is only 32 bit
