### ISSUE TITLE
Mortal Kombat Gold

### ISSUE THREAD

**Issue by WiksonDixon** [Rinnegatamante/flycast-vita-Compatibility#87]
# Game summary
- Game name: Mortal Kombat Gold 
- Game version: 1.000 (CDI)

# flycast summary
- Version: Latest Release Build (Normal Mode)

# Issues
- FMV Is stuttering (15 fps) Menus are fine, around 55-60fps, Ingame 17-20fps. No graphical glitches except "Choose your destiny" screen.

# Screenshots
- All my screenshots are corrupted, sorry.

# Recommended labels
- Ingame+

**Comment by Shinriji** [comment]
Same as #27
